export const BUS_TYPE_COLOR_CLASS_MAP: Record<number, string> = {
  1: "bg-(--bus-green)",
  2: "bg-(--bus-blue)",
  3: "bg-(--bus-green)",
  4: "bg-(--bus-red)",
  5: "bg-(--bus-sky)",
  6: "bg-[var(--bus-purple)]",
  10: "bg-[var(--bus-slate)]",
  11: "bg-(--bus-blue)",
  12: "bg-(--bus-green)",
  13: "bg-[var(--bus-amber)]",
  14: "bg-(--bus-red)",
  15: "bg-[var(--bus-orange)]",
  16: "bg-[var(--bus-violet)]",
  20: "bg-[var(--bus-lime)]",
  22: "bg-[var(--bus-dark-red)]",
  26: "bg-[var(--bus-deep-purple)]",
  30: "bg-[var(--bus-cyan)]",
};

export const BUS_TYPE_TEXT_COLOR_MAP: Record<number, string> = {
  1: "var(--bus-green)",
  2: "var(--bus-blue)",
  3: "var(--bus-green)",
  4: "var(--bus-red)",
  5: "var(--bus-sky)",
  6: "var(--bus-purple)",
  10: "var(--bus-slate)",
  11: "var(--bus-blue)",
  12: "var(--bus-green)",
  13: "var(--bus-amber)",
  14: "var(--bus-red)",
  15: "var(--bus-orange)",
  16: "var(--bus-violet)",
  20: "var(--bus-lime)",
  22: "var(--bus-dark-red)",
  26: "var(--bus-deep-purple)",
  30: "var(--bus-cyan)",
};

export const SUBWAY_CODE_COLOR_MAP: Record<number, string> = {
  1: "var(--line-1)",
  2: "var(--line-2)",
  3: "var(--line-3)",
  4: "var(--line-4)",
  5: "var(--line-5)",
  6: "var(--line-6)",
  7: "var(--line-7)",
  8: "var(--line-8)",
  9: "var(--line-9)",
  21: "var(--line-incheon-1)",
  22: "var(--line-incheon-2)",
  91: "var(--line-gtx-a)",
  101: "var(--line-airport)",
  102: "var(--line-airport)",
  104: "var(--line-gyeongui)",
  107: "var(--line-ever)",
  108: "var(--line-gyeongchun)",
  109: "var(--line-sinbundang)",
  110: "var(--line-uijeongbu)",
  112: "var(--line-gyeonggang)",
  113: "var(--line-ui-sinseol)",
  114: "var(--line-seohae)",
  115: "var(--line-gimpo-gold)",
  116: "var(--line-su-in-bundang)",
  117: "var(--line-sillim)",
};
